make svg, use Gnuplot 5.0.4
./get-new-stats.py doesn't work with Python 3.5.2 in Linux Mint 18:

  $ ./get-new-stats.py
  Traceback (most recent call last):
    File "./get-new-stats.py", line 25, in <module>
      chart = json.loads(get_http('https://www.openhub.net/repositories/chart'))
    File "./get-new-stats.py", line 21, in get_http
      str_response = response.readall().decode('utf-8')
  AttributeError: 'HTTPResponse' object has no attribute 'readall'
  $

It works in Debian 8.7 with Python 3.4.2. Seems as some kind of
incompatibility has been introduced, probably in Python 3.5.0. Not cool.
Whatever. I'll just execute the script on this computer instead.

5b53f89a-eb30-11e6-89fa-db5caa6d21d3